### ISSUE TITLE
2.0.0 needs to be released in RubyGems

### ISSUE THREAD

**Issue by adaddeo** [street-address-rb/street-address#32]
Por favor.

**Comment by leifg** [comment]
+1

**Comment by lehresman** [comment]
Any chance of this happening soonish?

**Comment by zhon** [comment]
Is 2.0.0 not ready for prime time?

**Comment by jnmandal** [comment]
Over a year since this is opened, should we just fork it and release that?

**Comment by zhon** [comment]
Very tempting. I have a private streetaddress I am currently using.

**Comment by derrek** [comment]
I won't have time to work on this for at least the next three months.  I'm ok transferring ownership of this repo and the gem to a volunteer.

**Comment by jnmandal** [comment]
Thanks for response @derrek. I nominate @zhon since hes already using it otherwise I don't mind doing it.

**Comment by jsmestad** [comment]
I am happy to contribute!

**Comment by zhon** [comment]
I don't mind doing it, except it will be a couple of weeks before I could get to it.

I also like moving it the street-address/street-address and adding a couple of other owners.

**Comment by derrek** [comment]
I think moving it and having multiple collaborators is a decent proposition given my current constraints.

**Comment by derrek** [comment]
@jsmestad would you like to collaborate on street-address as well?

**Comment by derrek** [comment]
I set up street-address-rb.  Need to do a quick bit of research to see if I  think its best to transfer this repo there or fork it into there.

**Comment by johnnagro** [comment]
let me know if i can help

**Comment by drews256** [comment]
Any update on this @derrek?

**Comment by derrek** [comment]
@drews256: I set up street-address-rb org and invited members.  Non of the invites were accepted. 
 
That said I didn't follow through much.  Anyone on this thread willing to help maintain it? @zhon @jnmandal @jsmestad

**Comment by jaydorsey** [comment]
I'll volunteer to help co-maintain it

**Comment by derrek** [comment]
@jaydorsey can you email me at derrek dot long at gmail

**Comment by jaydorsey** [comment]
Will do. I got your invite last night and accepted

**Comment by jnmandal** [comment]
Hey @derrek I'm happy to help as well! I dont think I got an invite 🤔

**Comment by derrek** [comment]
@jnmandal invited

**Comment by derrek** [comment]
Alright the repo has been moved to https://github.com/street-address-rb/street-address

Slow but steady progress...

**Comment by jaydorsey** [comment]
@derrek I'm still happy to help with this repo if you're interested. I sent you an email but understand you might be busy. Feel free to reach out when you're ready.

**Comment by jnmandal** [comment]
Seems @derrek is p. busy; @zhon, @jaydorsey what do you all see as the steps we need to take to ensure the 2.0.0 is robust enough for a release? 

Currently I'm using a fork of master in production for my app with no issues (https://github.com/compost-connect/street-address). Anyone else doing something similar?

**Comment by zhon** [comment]
I have a small monkey patch to the released version (1.0.6) where I modify the way addresses are output. This works for me on Ruby 2.3. I have not even tested the master.

There are 3 unresolved patches we might want to look at. 

I would like to see the test coverage metrics and see all the test passing.

**Comment by jaydorsey** [comment]
@jnmandal I'm using a fork as well. The only changes I made are slight to the Gemfile to make it easier to use when you're pointing to the repo instead of using the gem.

I'd probably want to give it a full lookover including the outstanding PRs per @zhon 

Also, I think a few of the issues (US/United States) could be quickly and easily addressed

I didn't want to jump into anything without chatting w/ @derrek first. Plus, he may be the only person with access to push to rubygems?

**Comment by zhon** [comment]
For @derrek to add a new owner, it only takes the following:

``$ gem owner --add {{email}} {{gem}}``

**Comment by jaydorsey** [comment]
@zhon @jnmandal I chatted w/ @derrek briefly via email last week. He's swamped right now but is going to grant access to rubygems to one or more of us soon.

I'm currently using a fork of master. The only change I really made was to update the spec file so that the gemspec name is `street_address` to comport with what you commonly see in gems. IIRC, that made it slightly more intuitive to reference using it inside of a gemspec (e.g. `gem/add_development_dependency 'street_address'` vs `StreetAddress`)

Other than that, I figured I'd look at the 3 open PRs, run thru the issues list and curate it and see if there are any low hanging issues we can resolve immediately (the two for US/USA might be as easy as a regex/delete and 2 extra tests), and make sure the tests are passing.

I've been using this for a month or two now and for the most part is "just works" so I think other than the curation above a new release could be done relatively quickly.

Thoughts?

**Comment by zhon** [comment]
I like your thinking. I think we should have working release asap.

**Comment by darrenleeweber** [comment]
https://rubygems.org/gems/StreetAddress/ - 1.0.6 is still the latest.  A changelog for a major version bump would be good.

**Comment by gurgeous** [comment]
Bump. This is a nice gem - let's bring it back to life!

**Comment by derrek** [comment]
Is anyone using the github master branch in production?  I'd like to hear about it. If all is well we can push a 2.0 gem.  I held off releasing 2.0, a long time ago, because there were some huge regression issues then haven't been able to work in this space since.

**Comment by gurgeous** [comment]
No worries. Just happy to resuscitate the repo in some form, even if changed or slightly broken! I'm on an old version, not master. Want to take a stab at a changelog section in the README? Maybe I can help with testing.

**Comment by adaddeo** [comment]
I'm closing this issue, don't think it'll be resolved. Hopefully someone forks and maintains!

**Comment by swamyg** [comment]
Any chance of release the 2.0 gem? I'm having version conflict when using this gem inside a custom gem that gets used in another project. The custom gem is working off of GitHub master (of this repo), but the project that is using that gem says 
```Could not find gem 'StreetAddress (~> 2.0.0)', which is required by gem 'property_service', in any of the sources.```

It'd be great if StreetAddress 2.0.0 can be released to RubyGems.
